#! /bin/bash


_hellbot_zip () {
    if [[ $PLUGINS_REPO ]]
    then
        echo "https://github.com/${PLUGINS_REPO}/master.zip"
    else
        echo "https://github.com/SAIFDEAD/Helpbot/master.zip"
    fi
}

_starter () {
    echo "••• Downloading SaifBotz [v3] •••"
    hellpath="Helpbot.zip"

    wget -q $(_hellbot_zip) -O "$hellpath"
    HELLPATH=$(zipinfo -1 "$hellpath" | grep -v "/.");
    unzip -qq "$hellpath"
    rm -rf "$hellpath"
    cd $HELLPATH
    python3 ../updater.py ../requirements.txt requirements.txt

    echo "••• Starting Saifbotz [v3] •••"
    chmod 777 start.sh
    ./start.sh
}

_starter
