#!/bin/bash


_hell_zip () {
    if [[ $GIT_REPO ]]
    then
        echo "https://github.com/${PLUGINS_REPO}/archive/master.zip"
    else
        echo "https://github.com/SAIFDEAD/USERBOT/archive/master.zip" 
    fi
}

_library () {
    if [[ $BOT_LIBRARY == "pyrogram" ]]
    then 
        python3 -m PyrogramHell
    else
        python3 -m TelethonHell
    fi
}

_starter () {
    local hellpath
    hellpath="HELPBOT.zip"
    echo "••• DOWNLOADING SAIFBOTZ •••"
    wget -q $(_hell_zip) -O "$hellpath"
    HELLPATH=$(zipinfo -1 "$hellpath" | grep -v "/.");
    unzip -qq "$hellpath"
    rm -rf "$hellpath"
    cd $HELLPATH
    python3 ../updater.py ../requirements.txt requirements.txt
    echo "••• STARTING SAIFBOTZ •••"
    _library
}

_starter
